### ISSUE TITLE
disconnect after 5 min

### ISSUE THREAD

**Issue by Nir-betesh** [almogkh/EKrut-project#64]
After user is disconnecting automatically  and signs in back he can not move to new order.
I believe that the bug is in the time implementation.

**Comment by almogkh** [comment]
In the current code on GitHub there is no way to access the order screen as far as I can tell. The "create new order" button doesn't do anything. I just tested and after being logged out by the system and logging back in, The "create new order" button was still there. So this means the bug is in your code which you haven't pushed yet.

**Comment by Nir-betesh** [comment]
Ok, I will check it.
